import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]

opacity = 1

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "Cascadia Code "
bold.family = "Cascadia Code "
italic.family = "Cascadia Code "
bold_italic.family = "Cascadia Code "

size = 14.0

[env]
TERM = "xterm-256color"

