#!/usr/bin/env sh
# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config window_gap 20
yabai -m config top_padding 25
#yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/scripts/set_padding.py"
yabai -m config bottom_padding 15
yabai -m config right_padding 20
yabai -m config left_padding 20

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
# left click and drag
yabai -m config mouse_action1 move
# right click and drag
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# disable yabai for these apps
#yabai -m rule --add app="^Discord$" manage=off
