#!/usr/bin/env sh
# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config window_gap 20

#yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/scripts/set_padding.py"
yabai -m config bottom_padding 15
yabai -m config right_padding 15
yabai -m config left_padding 15

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
# left click and drag
yabai -m config mouse_action1 move
# right click and drag
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap


# when a space is focused
yabai -m signal --add event=space_changed action="~/dotfiles/config/yabai/scripts/set_display_padding.sh"
# when a display is focused (if you frequently switch between displays)
yabai -m signal --add event=display_changed action="~/dotfiles/config/yabai/scripts/set_display_padding.sh"


# disable yabai for these apps

#yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
# run borders service
borders &
